# Generated by Django 3.1.3 on 2020-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField()),
                ('adhar', models.CharField(max_length=12, unique=True)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('work', models.CharField(choices=[('painters', 'painters'), ('carpenter', 'carpenter'), ('handloom worker', 'handloom worker'), ('labour', 'labour')], default='labour', max_length=100)),
                ('other', models.CharField(blank=True, default=None, max_length=100)),
                ('is_registered', models.BooleanField(blank=True, default=None)),
                ('is_employed', models.BooleanField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
