# Generated by Django 3.1.3 on 2020-11-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adhar',
        ),
        migrations.RemoveField(
            model_name='company',
            name='dob',
        ),
    ]
