# Generated by Django 3.1.3 on 2020-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('slug', models.SlugField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('requirement_type', models.CharField(choices=[('painters', 'painters'), ('carpenter', 'carpenter'), ('handloom worker', 'handloom worker'), ('labour', 'labour')], default='labour', max_length=100)),
                ('other', models.CharField(blank=True, default=None, max_length=100)),
                ('address', models.TextField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers ',
            },
        ),
    ]
