# Generated by Django 3.1.3 on 2020-11-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_employer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
    ]
