# Generated by Django 3.1.3 on 2020-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_auto_20201107_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={},
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='works_for',
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_employed',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_registered',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='worker',
            name='other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
