# Generated by Django 3.1.3 on 2020-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_auto_20201107_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='work',
            field=models.CharField(choices=[('carpenter', 'carpenter'), ('handloom worker', 'handloom worker'), ('labour', 'labour')], default='labour', max_length=100),
        ),
    ]
